<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DonkeyWork.Recordings.Identity.Contracts\DonkeyWork.Recordings.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\common\DonkeyWork.Recordings.Persistence\DonkeyWork.Recordings.Persistence.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
